########################################################################
### Makefile
###

### application forth sources
APP_FSRCS=

### application c sources
APP_CSRCS=

### build/exec env -- see plat/tgt-*
TGT=linux

### load up the boilerplate stuff
include Make.targets

### EOF Makefile

